### ISSUE TITLE
go build -mod vendor' returned a non-zero code: 

### ISSUE THREAD

**Issue by oskarth** [status-im/status-protocol-go-bandwidth-test#1]
```
oskarth@localhost /home/oskarth/git/status-im/status-protocol-go-bandwidth-test> ./run.rb -m 0 -s 20 -a 2 -d -g
Traceback (most recent call last):
	3: from ./run.rb:44:in `<main>'
	2: from /usr/share/gems/gems/docker-api-1.34.2/lib/docker/image.rb:293:in `build_from_dir'
	1: from /usr/share/gems/gems/docker-api-1.34.2/lib/docker/image.rb:281:in `build_from_tar'
 (Docker::Error::UnexpectedResponseError)b/docker/util.rb:200:in `extract_id': Couldn't find id: {"stream":"Step 1/5 : FROM golang:1.12"}
{"stream":"\n"}
{"stream":" ---\u003e 381475b19c9f\n"}
{"stream":"Step 2/5 : WORKDIR /app"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 9229c1683a77\n"}
{"stream":"Step 3/5 : ADD . /app"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 1e3796482843\n"}
{"stream":"Step 4/5 : RUN go build -mod vendor"}
{"stream":"\n"}
{"stream":" ---\u003e Running in bdebeacd24d4\n"}
{"stream":"\u001b[91m# github.com/status-im/status-go/discovery\nvendor/github.com/status-im/status-go/discovery/proxy.go:126:12: undefined: enr.SignV4\n\u001b[0m"}
{"stream":"\u001b[91m# gopkg.in/olebedev/go-duktape.v3\nduk_logging.c: In function 'duk__logger_prototype_log_shared':\nduk_logging.c:184:64: warning: 'Z' directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]\n  sprintf((char *) date_buf, \"%04d-%02d-%02dT%02d:%02d:%02d.%03dZ\",\n                                                                ^\nduk_logging.c:184:2: note: 'sprintf' output between 25 and 85 bytes into a destination of size 32\n  sprintf((char *) date_buf, \"%04d-%02d-%02dT%02d:%02d:%02d.%03dZ\",\n  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n          (int) comp.year, (int) comp.month + 1, (int) comp.day,\n          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n          (int) comp.hours, (int) comp.minutes, (int) comp.seconds,\n          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n          (int) comp.milliseconds);\n          ~~~~~~~~~~~~~~~~~~~~~~~~\n\u001b[0m"}
{"errorDetail":{"code":2,"message":"The command '/bin/sh -c go build -mod vendor' returned a non-zero code: 2"},"error":"The command '/bin/sh -c go build -mod vendor' returned a non-zero code: 2"}
```

@cammellos @adambabik

**Comment by oskarth** [comment]
More minimal, I suppose related to monorepo move?

```
oskarth@localhost /home/oskarth/git/status-im/status-protocol-go-bandwidth-test> docker build -t foo .
Sending build context to Docker daemon  62.36MB
Step 1/5 : FROM golang:1.12
 ---> 381475b19c9f
Step 2/5 : WORKDIR /app
 ---> Using cache
 ---> 9229c1683a77
Step 3/5 : ADD . /app
 ---> 11fbfb2574ad
Step 4/5 : RUN go build -mod vendor
 ---> Running in dd69c5b3dffa

# github.com/status-im/status-go/discovery
vendor/github.com/status-im/status-go/discovery/proxy.go:126:12: undefined: enr.SignV4
# gopkg.in/olebedev/go-duktape.v3
duk_logging.c: In function 'duk__logger_prototype_log_shared':
duk_logging.c:184:64: warning: 'Z' directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
                                                                ^
duk_logging.c:184:2: note: 'sprintf' output between 25 and 85 bytes into a destination of size 32
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.year, (int) comp.month + 1, (int) comp.day,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.hours, (int) comp.minutes, (int) comp.seconds,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.milliseconds);
          ~~~~~~~~~~~~~~~~~~~~~~~~
The command '/bin/sh -c go build -mod vendor' returned a non-zero code: 2
```

```
oskarth@localhost /home/oskarth/git/status-im/status-protocol-go-bandwidth-test> go build -mod vendor
# gopkg.in/olebedev/go-duktape.v3
duk_logging.c: In function ‘duk__logger_prototype_log_shared’:
duk_logging.c:184:64: warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
                                                                ^
duk_logging.c:184:2: note: ‘sprintf’ output between 25 and 85 bytes into a destination of size 32
  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.year, (int) comp.month + 1, (int) comp.day,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.hours, (int) comp.minutes, (int) comp.seconds,
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          (int) comp.milliseconds);
          ~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/status-im/status-go/discovery
vendor/github.com/status-im/status-go/discovery/proxy.go:126:12: undefined: enr.SignV4
```
